export const POLICE_CONFIG = Object.freeze({
  difficulty: .5,
  normalSpeedRatio: .80,
  slowPlayerSpeedRatio: .95,
  slowPlayerThreshold: 7,
  acceleration: 4,
  braking: 10,
  routeUpdateMin: 1.05,
  routeUpdateMax: 1.45,
  moderateTurnRatio: .75,
  sharpTurnRatio: .58,
  cornerLookahead: 24,
  turnReactionSeconds: .18,
  yawRate: 2.5,
  spawnDistance: 185,
  spawnDistanceMin: 170,
  spawnDistanceMax: 220,
  graceSeconds: 4,
});
