export const POLICE_CONFIG = Object.freeze({
  difficulty: .8,
  normalSpeedRatio: .94,
  slowPlayerSpeedRatio: 1.07,
  slowPlayerThreshold: 7,
  acceleration: 5.5,
  braking: 12,
  routeUpdateMin: .45,
  routeUpdateMax: .75,
  moderateTurnRatio: .88,
  sharpTurnRatio: .74,
  cornerLookahead: 24,
  turnReactionSeconds: .07,
  yawRate: 3.5,
  boostDuration: 4,
  boostCooldown: 8,
  catchupDistance: 250,
  catchupReleaseDistance: 120,
  maxCatchupRatio: 1.07,
  spawnDistance: 185,
  spawnDistanceMin: 170,
  spawnDistanceMax: 220,
  graceSeconds: 4,
});
